name: 'Publish Docker Image'
description: 'Faz login no Docker Hub, builda e faz push da imagem Docker.'
inputs:
  dockerhub-username:
    description: 'Docker Hub username'
    required: true
  dockerhub-password:
    description: 'Docker Hub password or access token'
    required: true
  image-name:
    description: 'Docker image name (e.g. user/repo)'
    required: true
  build-context:
    description: 'Docker build context (default: .)'
    required: false
    default: '.'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-password }}

    - name: Build Docker image
      run: docker build -t ${{ inputs.image-name }} ${{ inputs.build-context }}
      shell: bash

    - name: Push Docker image
      run: docker push ${{ inputs.image-name }}
      shell: bash
